import "./globals.css";
import "@/public/fonts/Space/stylesheet.css";
import "@/public/fonts/overused/stylesheet.css";
import Navbar from "@/components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" pt-[6rem] w-full relative bg-black">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
